global using Genesphere;
global using GenesysCloud.QueryHandlers.Contracts;
global using GenesysCloud.QueryHandlers.Mock;
global using GenesysCloud.QueryHandlers.PureCloud;
global using GenesysCloud.Services;
global using GenesysCloud.Services.Contracts;
global using GenesysCloud.DTO;
global using GenesysCloud.Helpers;
global using Microsoft.AspNetCore.Mvc;